"""init

Revision ID: dde8220e9f5a
Revises: 
Create Date: 2024-07-14 12:17:00.822809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde8220e9f5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('cust_firstname', sa.String(), nullable=False),
    sa.Column('cust_lastname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cust_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=False),
    sa.Column('item_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('order_qty', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['customers.cust_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('items')
    op.drop_table('customers')
    # ### end Alembic commands ###
